model_config:
  albef:
    bert_model_name: bert-base-uncased
    direct_features_input: false
    num_labels: 2
    num_features: 1

    image_encoder:
      type: albef_vit_encoder
      params:
        img_size: 334
        out_dim: 768
        patch_size: 16
        in_chans: 3
        depth: 12
        num_heads: 12
        mlp_ratio: 4.0
        qkv_bias: true
        
    text_encoder:
      type: albef_bert_encoder
      params:
        bert_model_name: bert-base-uncased
        hidden_size: 768
        num_hidden_layers: 12
        num_attention_heads: 12
        output_attentions: false
        output_hidden_states: false

    classifier:
      type: mlp
      params:
        in_dim: 768
        out_dim: 2
        hidden_dim: 768
        num_layers: 2